### ISSUE TITLE
Butterfly effect

### ISSUE THREAD

**Issue by NikTuzov** [lvdmaaten/bhtsne#64]
Hello Laurens:

There is a sizeable difference in the output quantities when the difference between the input data sets is virtually zero. The R code attached below provides an illustration, and a similar issue exists with your code as well. I know it's all about relative distances among the points, so as long as the visualizations look similar (which is the case) the user shouldn't care. Still, it would be nice to see more consistent numbers in the output when the input data are virtually the same.

Based on my tests, the divergence occurs in computeNonEdgeForces() which causes computeGradient() to diverge as well.

Regards,
Nik Tuzov, PhD

===============================================

library(Rtsne)
library(rgl)

set.seed(115)
iris_unique <- unique(iris)
Y_zero <-  as.matrix(iris_unique[, 1:3])
tsne_out3d <- Rtsne(as.matrix(iris_unique[, 1:4]), dims = 3, Y_init = Y_zero)
plot3d(tsne_out3d$Y[, 1], tsne_out3d$Y[, 2], tsne_out3d$Y[, 3], col = as.numeric(iris_unique$Species))
head(tsne_out3d$Y)

set.seed(115)
iris_unique_butt = iris_unique;
iris_unique_butt[1, 1] = iris_unique_butt[1, 1] + 1e-6;
tsne_out3d_butt <- Rtsne(as.matrix(iris_unique_butt[, 1:4]), dims = 3, Y_init = Y_zero)
plot3d(tsne_out3d_butt$Y[, 1], tsne_out3d_butt$Y[, 2], tsne_out3d_butt$Y[, 3], col = as.numeric(iris_unique$Species))
head(tsne_out3d_butt$Y)

**Comment by lvdmaaten** [comment]
Given the nature of the Barnes-Hut approximation, this is not so surprising, is it? A small change in a single data point may push it from one quadrant to another, thereby changing the output of `computeNonEdgeForces()` because both some summary statistics as well as the pruning may change. This change then starts propagating for potentially many hundreds of iterations, which may lead to a different solution. I'm not quite sure what you want me to do about this?

**Comment by NikTuzov** [comment]
Does it make sense to apply some averaging like it is done in random forest, or you can always say that of two or more solutions one is the best, so there is no point in averaging them?

**Comment by lvdmaaten** [comment]
You could try, but it would substantially increase the computational costs at potentially limited gains.
